routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DevicesController;
use App\Http\Controllers\ReqMaintenanceController;
use App\Http\Controllers\HandelrequestController;
use App\Http\Controllers\UserProfileController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});


Route::middleware(['auth', 'authcheck'])->group(function () {
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::get('/nextHome', [HandelrequestController::class, 'nextHome']);
});

Auth::routes(['verify' => true]);

Route::middleware(['auth'])->group(function () {
    Route::get('devices/return_date/{id}', [DevicesController::class, 'return_date']);
    // Route::post('devices/return_date/{id}/update', [DevicesController::class, 'Requpdate']);
    Route::Post('/devices/return_date/updateme/{id}', [DevicesController::class, 'Requpdate']);
    Route::post('/HandleRequest/updatefirst/{id}', [HandelrequestController::class, 'updatefirst']);
    Route::post('/HandleRequest/updatesecond/{id}', [HandelrequestController::class, 'updatesecond']);
    Route::post('/HandleRequest/updatethird/{id}', [HandelrequestController::class, 'updatethird']);
    Route::get('HandleRequest/view/{id}', [HandelrequestController::class, 'view']);
    Route::post('/userprofile/ban/{id}', [UserProfileController::class, 'ban']);
    Route::post('/userprofile/ban/{id}', [UserProfileController::class, 'notban']);
    Route::Post('HandleRequest/remarks/{id}', [HandelrequestController::class, 'remarks']);
    Route::get('profile/{id}', [UserProfileController::class, 'show']);
    Route::get('userprofile/view/{id}', [UserProfileController::class, 'view']);

    Route::get('devices/export/', [DevicesController::class, 'export']);

    Route::resource('userprofile', UserProfileController::class);
    Route::resource('devices', DevicesController::class);
    Route::resource('requestMan', ReqMaintenanceController::class);
    Route::resource('HandleRequest', HandelrequestController::class);
});

app/Models/Devices.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Devices extends Model
{
    protected $fillable = ['name', 'date','return_date'];
    use HasFactory;
      
}

app/Http/Controllers/DevicesController.php
<?php

namespace App\Http\Controllers;

use Auth;
use App\Http\User;
use App\Models\Devices;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Http\Request\devices\UpdateDeviceRequest;
use Maatwebsite\Excel\Facades\Excel;

use App\Exports\DevicesExport;;


class DevicesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        return view('devices.index')->with('devices', Devices::all());
    }
    public function export(Request $request)
    {

       $request->session()->flash('message','Excel File Downloaded Successfully');
        return Excel::download(new DevicesExport, 'devices.xlsx');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Devices $devices)
    {
        return view('devices.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'date' => 'required',
            'return_date' => 'required',
            // 'user_id'=>'required'
        ]);
        Devices::create([
            'name' => $request->name,
            'date' => $request->date,
            'return_date' => $request->return_date,
            // 'user_id'=>$request->user_id
        ]);
        $request->session()->flash('message', 'Device Successfully added');
        return redirect(route('devices.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Devices  $devices
     * @return \Illuminate\Http\Response
     */
    public function show(Devices $devices)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Devices  $devices
     * @return \Illuminate\Http\Response
     */
    public function edit(Devices $device)
    {
        return view('devices.create')->with('device', $device);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Devices  $devices
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Devices $device)
    {
        $device->name = $request->name;
        $device->date = $request->date;
        $device->save();
        $request->session()->flash('message', 'Device Edited Successfully');
        return redirect(route('devices.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Devices  $devices
     * @return \Illuminate\Http\Response
     */
    public function destroy(Devices $device)
    {
        $device->delete();
        return redirect(route('devices.index'));
        $device->delete();
    }
    public function return_date(Request $request, Devices $id)
    {
        // $data=Device::all();
        return view('devices.reqMan')->with('devices', $id);
    }
    public function Requpdate(Request $request, Devices $id)
    {
        $this->validate($request, [
            'name' => 'required',
            'date' => 'required',
            'return_date' => 'required',
        ]);
        $id->name = $request->name;
        $id->date = $request->date;
        $id->return_date = $request->return_date;
        $id->save();
        $request->session()->flash('message', 'Return Date Successfull');
        return redirect(route('devices.index'));
    }
}

resources/views/devices/create.blade.php
@extends('layouts/app')
@section('content')

    <div class="card-card-default">
        <div class="card-header">
            <h4>{{ isset($device) ? 'Edit Devices' : 'Create Devices' }}</h4>
        </div>
        <div class="card-body">
            @if ($errors->any())
                <div class="alert alert-danger" role="alert">
                    @foreach ($errors->all() as $error)
                        <ul class="list-group">
                            <li class="list group-item">
                                {{ $error }}
                            </li>
                        </ul>
                    @endforeach
                </div>
            @endif

            <form action="{{ isset($device) ? route('devices.update', $device->id) : route('devices.store') }}"
                method="post">
                @csrf
                @if (isset($device))
                    @method('PUT')
                @endif
                {{-- <input type="text" class="form-control" name="name" value="{{ isset($devices) ? $devices->name:auth()->user()->id }}" > --}}
                <div class="form-group">
                    <label for="name">device model name</label>
                    <input type="text" class="form-control" name="name"
                        value="{{ isset($device) ? $device->name : '' }}">
                </div>
                <div class="form-group date" data-provide="datepicker">
                    <label for="date">Device taken date</label>
                    <input type="number" id="datepicker" class="form-control" name="date"
                        value="{{ isset($device) ? $device->date : '' }}">
                    <div class="input-group-addon">
                        <span class="glyphicon glyphicon-th"></span>
                    </div>
                </div>
                <input type="hidden" class="form-control" name="return_date" value="Not Return">

                <div class="form-group">
                    <button type="submit"
                        class="btn btn-success">{{ isset($device) ? 'Update device' : 'Add devices' }}</button>
                </div>
            </form>
        </div>
    </div>
@endsection

@section('scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.3.1/trix.js"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>

    <script>
        flatpickr('#datepicker')

    </script>
@endsection


@section('css')
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
@endsection

resources/views/devices/excel.blade.php
<table>
    <thead>
    <tr>
        <th>Name</th>
        <th>Email</th>
    </tr>
    </thead>
    <tbody>
    @foreach($devices as $devices)
        <tr>
            <td>{{ $devices->name }}</td>
            <td>{{ $devices->date }}</td>
        </tr>
    @endforeach
    </tbody>
</table>

resources/views/devices/index.blade.php
@extends('layouts/app')
@section('datatable')
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.23/css/jquery.dataTables.css">
@endsection
@section('content')
    @if (session()->has('message'))
        <div class="alert alert-success" role="alert">
            {{ session()->get('message') }}
        </div>
    @endif
    <div class="d-flex justify-content-end mb-2">
        <a href="{{ route('devices.create') }}" class="btn btn-success">Add Devices</a>
    </div>
    <div class="card">
        <div class="card-header bg-info">
            <h4>Devices</h4>
        </div>
        <div class="card-body">
            <h5 class="card-title ">View Your Profile</h5>
            <table class="table table-bordered" id="table_id">
                <thead>
                    <tr>
                        <th scope="col">Device Model Name</th>
                        <th scope="col">Device Taken Date</th>
                        <th scope="col">Device Return Date</th>
                        <th>Action</th>
                    </tr>
                </thead>
                @foreach ($devices as $device)
                    <tbody>

                        <td>{{ $device->name }}</td>
                        <td>{{ $device->date }}</td>
                        <td>{{ $device->return_date }}</td>
                        <td>
                            <a href="{{ route('devices.edit', $device->id) }}" class="btn btn-primary btn-sm">Edit</a>
                            <button class="btn btn-danger btn-sm"
                                onclick="handleDelete({{ $device->id }})">Delete</button>

                            @if ($device->return_date == 'Not Return')
                                <button class="btn btn-success btn-sm" onclick="handleDelete1({{ $device->id }})">Return
                                    Device </button>
                            @else

                            @endif
                        </td>

                    </tbody>
                    @endforeach

            </table>
            <!-- Modal -->
            <div class="modal fade" id="DeleteModel" tabindex="-1" aria-labelledby="DeleteModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <form action="" method="POST" id="deleteform">
                        @csrf
                        @method('DELETE')
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="DeleteModalLabel">Pending</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                Are You Sure you want to delete?
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">No, Go Back</button>
                                <button type="submit" class="btn btn-primary">Yes</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <!-- Modal -->
            <div class="modal fade" id="ReturnModel1" tabindex="-1" aria-labelledby="returnModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <form action="" method="POST" id="ReturnDate">
                        @csrf
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="returnModalLabel">Return Device</h5>
                                <input type="hidden" class="form-control" name="name" value="{{isset($device)?$device->name:''}}">
                                <input type="hidden" class="form-control" name="date" value="{{isset($device)?$device->name:''}}">
                                <input type="hidden" class="form-control" name="return_date"
                                    value="{{ date('Y-m-d H:i:s') }}">
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                Do you Want To return the devices?
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">No, Go Back</button>
                                <button type="submit" class="btn btn-primary">Yes</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    @endsection

    @section('scripts')

        <script>
            function handleDelete(id) {
                var form = document.getElementById('deleteform');
                form.action = '/devices/' + id
                $('#DeleteModel').modal('show')
            }

        </script>
        <script>
            function handleDelete1(id) {
                var form = document.getElementById('ReturnDate');
                form.action = '/devices/return_date/updateme/' + id
                $('#ReturnModel1').modal('show')
            }

        </script>

    @endsection
    @section('datatablescript')
        <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.js">
        <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
        </script>

        <script>
            $(document).ready(function() {
                $('#table_id').DataTable();
            });

        </script>
    @endsection

resources/views/devices/reqMan.blade.php
@extends('layouts/app')
@section('content')

    <div class="card-card-default">
        <div class="card-header">
            <h4>date_return</h4>
        </div>
        <div class="card-body">
            @if ($errors->any())
                <div class="alert alert-danger" role="alert">
                    @foreach ($errors->all() as $error)
                        <ul class="list-group">
                            <li class="list group-item">
                                {{ $error }}
                            </li>
                        </ul>
                    @endforeach
                </div>
            @endif

            <form action="{{ url('devices/return_date/' . $devices->id . '/update') }}" method="post">
                @csrf

                <input type="hidden" class="form-control" name="name" value="{{ $devices->name }}">
                <input type="hidden" class="form-control" name="date" value="{{ $devices->name }}">
                <input type="text" class="form-control" name="return_date" value="{{ date('Y-m-d H:i:s') }}">
                <br>

                <div class="form-group">
                    <button type="hidden" class="btn btn-success">submit</button>
                </div>
            </form>
        </div>
    </div>
@endsection

@section('script')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.3.1/trix.js"></script>
@endsection

@section('css')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.3.1/trix.js">
@endsection