routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DevicesController;
use App\Http\Controllers\ReqMaintenanceController;
use App\Http\Controllers\HandelrequestController;
use App\Http\Controllers\UserProfileController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});


Route::middleware(['auth', 'authcheck'])->group(function () {
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::get('/nextHome', [HandelrequestController::class, 'nextHome']);
});

Auth::routes(['verify' => true]);

Route::middleware(['auth'])->group(function () {
    Route::get('devices/return_date/{id}', [DevicesController::class, 'return_date']);
    // Route::post('devices/return_date/{id}/update', [DevicesController::class, 'Requpdate']);
    Route::Post('/devices/return_date/updateme/{id}', [DevicesController::class, 'Requpdate']);
    Route::post('/HandleRequest/updatefirst/{id}', [HandelrequestController::class, 'updatefirst']);
    Route::post('/HandleRequest/updatesecond/{id}', [HandelrequestController::class, 'updatesecond']);
    Route::post('/HandleRequest/updatethird/{id}', [HandelrequestController::class, 'updatethird']);
    Route::get('HandleRequest/view/{id}', [HandelrequestController::class, 'view']);
    Route::post('/userprofile/ban/{id}', [UserProfileController::class, 'ban']);
    Route::post('/userprofile/ban/{id}', [UserProfileController::class, 'notban']);
    Route::Post('HandleRequest/remarks/{id}', [HandelrequestController::class, 'remarks']);
    Route::get('profile/{id}', [UserProfileController::class, 'show']);
    Route::get('userprofile/view/{id}', [UserProfileController::class, 'view']);

    Route::get('devices/export/', [DevicesController::class, 'export']);

    Route::resource('userprofile', UserProfileController::class);
    Route::resource('devices', DevicesController::class);
    Route::resource('requestMan', ReqMaintenanceController::class);
    Route::resource('HandleRequest', HandelrequestController::class);
});

app/Models/Request.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Request extends Model
{
    use HasFactory;
}

resources/views/request/create.blade.php
@extends('layouts/app')
@section('content')

    <div class="card-card-default">
        <div class="card-header">Add Request</h4>
        </div>
        <div class="card-body">
            @if ($errors->any())
                <div class="alert alert-danger" role="alert">
                    @foreach ($errors->all() as $error)
                        <ul class="list-group">
                            <li class="list group-item">
                                {{ $error }}
                            </li>
                        </ul>
                    @endforeach
                </div>
            @endif

            <form action="{{ route('requestMan.store') }}" method="post" enctype="multipart/form-data">
                @csrf
                <input type="hidden" class="form-control" name="user_id" value="{{ auth()->user()->id }}">
                <div class="form-group">
                    <label for="subject">Subject</label>
                    <input type="text" class="form-control" name="subject" value="">
                </div>

                <div class="form-group">
                    <label for="description">Description</label>
                    <textarea name="description" class="form-control" id="" cols="20" rows="5"></textarea>
                </div>

                <div class="form-group">
                    <label for="name">Image</label>
                    <input type="file" class="form-control" name="image" value="">
                </div>

                <div class="form-group">
                    <label for="location">location</label>
                    <input type="text" class="form-control" name="location" value="">
                </div>
                <div class="form-group">
                    <input type="hidden" name="status" class="form-control" name="location" value="Pending">
                </div>

                <div class="form-group">
                    <button type="submit" class="btn btn-success">Add Request</button>
                </div>
            </form>
        </div>
    </div>
@endsection

@section('script')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.3.1/trix.js"></script>
@endsection

@section('css')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.3.1/trix.js">
@endsection

resources/views/request/index.blade.php
@extends('layouts/app')
@section('content')
    <div class="justify-content">
        <a href="{{ route('requestMan.create') }}" class="btn btn-success">Add Request</a>
    </div>
    <br>
    <div class="card-default">
        <div class="card-header">Request</div>
        <div class="card-body">

            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">subject</th>
                        <th scope="col">description</th>
                        <th scope="col">image</th>
                        <th scope="col">location</th>
                        <th scope="col">status</th>
                        <th scope="col">Remarks</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($reqMantinance as $requestMa)

                        <tr>
                            <td scope="row">{{ $requestMa->subject }}</th>
                            <td>{{ $requestMa->description }}</td>
                            <td><img src="{{ asset('storage/' . $requestMa->image) }}" alt="" height="50" width="50"></td>
                            <td>{{ $requestMa->location }}</td>
                            @if ($requestMa->status == 'Pending')
                                <td><button class="btn btn-danger" disabled>Pending</button></td>
                            @elseif($requestMa->status=='Processing')
                                <td><button class="btn btn-primary" disabled>Processing</button></td>
                            @else
                                <td><button class="btn btn-success" disabled>Completed</button></td>
                            @endif
                            <td>{{ $requestMa->remarks }}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection