routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DevicesController;
use App\Http\Controllers\ReqMaintenanceController;
use App\Http\Controllers\HandelrequestController;
use App\Http\Controllers\UserProfileController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});


Route::middleware(['auth', 'authcheck'])->group(function () {
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::get('/nextHome', [HandelrequestController::class, 'nextHome']);
});

Auth::routes(['verify' => true]);

Route::middleware(['auth'])->group(function () {
    Route::get('devices/return_date/{id}', [DevicesController::class, 'return_date']);
    // Route::post('devices/return_date/{id}/update', [DevicesController::class, 'Requpdate']);
    Route::Post('/devices/return_date/updateme/{id}', [DevicesController::class, 'Requpdate']);
    Route::post('/HandleRequest/updatefirst/{id}', [HandelrequestController::class, 'updatefirst']);
    Route::post('/HandleRequest/updatesecond/{id}', [HandelrequestController::class, 'updatesecond']);
    Route::post('/HandleRequest/updatethird/{id}', [HandelrequestController::class, 'updatethird']);
    Route::get('HandleRequest/view/{id}', [HandelrequestController::class, 'view']);
    Route::post('/userprofile/ban/{id}', [UserProfileController::class, 'ban']);
    Route::post('/userprofile/ban/{id}', [UserProfileController::class, 'notban']);
    Route::Post('HandleRequest/remarks/{id}', [HandelrequestController::class, 'remarks']);
    Route::get('profile/{id}', [UserProfileController::class, 'show']);
    Route::get('userprofile/view/{id}', [UserProfileController::class, 'view']);

    Route::get('devices/export/', [DevicesController::class, 'export']);

    Route::resource('userprofile', UserProfileController::class);
    Route::resource('devices', DevicesController::class);
    Route::resource('requestMan', ReqMaintenanceController::class);
    Route::resource('HandleRequest', HandelrequestController::class);
});

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous">
    </script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous">
    </script>


    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.23/css/jquery.dataTables.min.css">
    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <script src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"></script>

    @yield('datepicker')
    @yield('css')
    @yield('datatable')
</head>

<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/home') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            {{-- @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif --}}
                        @else
                            <div class="dropdown">
                                <button class="btn btn-outline-info dropdown-toggle" type="button" id="dropdownMenuButton"
                                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    {{ Auth::user()->name }}
                                </button>
                                <div class="dropdown-menu center" aria-labelledby="dropdownMenuButton ">
                                    <a class="btn btn-link"
                                        href="{{ url('profile/' . auth()->user()->id) }}">Profile</a><br>
                                    <a class="btn btn-link" href="{{ route('logout') }}" onclick="event.preventDefault();
                                            document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>
                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </div>

                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            <div class="container">
                @auth
                    <div class="row">
                        <div class="col-md-3">
                            <ul class="list-group">
                                @hasrole('admin')
                                <li class="list-group-item mb-2">
                                    <a href="{{ route('devices.index') }}">Devices</a>
                                </li>
                                <li class="list-group-item mb-2">
                                    <a href="{{ route('HandleRequest.index') }}">Handle Request</a>
                                </li>
                                <li class="list-group-item">
                                    <a href="{{ route('userprofile.index') }}">Users</a>
                                </li>


                            @else
                                <li class="list-group-item">
                                    <a href="{{ route('requestMan.index') }}">Request</a>
                                </li>
                                @endhasrole
                            </ul>
                        </div>
                        <div class="col-md-9">
                            @yield('content')
                        </div>
                    </div>
                @else
                    @yield('content')
                @endauth
            </div>
        </main>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous">
    </script>

    <script src="{{ asset('js/app.js') }}"></script>
    @yield('scripts')
    @yield('datatablescript')


</body>

</html>