routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DevicesController;
use App\Http\Controllers\ReqMaintenanceController;
use App\Http\Controllers\HandelrequestController;
use App\Http\Controllers\UserProfileController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});


Route::middleware(['auth', 'authcheck'])->group(function () {
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::get('/nextHome', [HandelrequestController::class, 'nextHome']);
});

Auth::routes(['verify' => true]);

Route::middleware(['auth'])->group(function () {
    Route::get('devices/return_date/{id}', [DevicesController::class, 'return_date']);
    // Route::post('devices/return_date/{id}/update', [DevicesController::class, 'Requpdate']);
    Route::Post('/devices/return_date/updateme/{id}', [DevicesController::class, 'Requpdate']);
    Route::post('/HandleRequest/updatefirst/{id}', [HandelrequestController::class, 'updatefirst']);
    Route::post('/HandleRequest/updatesecond/{id}', [HandelrequestController::class, 'updatesecond']);
    Route::post('/HandleRequest/updatethird/{id}', [HandelrequestController::class, 'updatethird']);
    Route::get('HandleRequest/view/{id}', [HandelrequestController::class, 'view']);
    Route::post('/userprofile/ban/{id}', [UserProfileController::class, 'ban']);
    Route::post('/userprofile/ban/{id}', [UserProfileController::class, 'notban']);
    Route::Post('HandleRequest/remarks/{id}', [HandelrequestController::class, 'remarks']);
    Route::get('profile/{id}', [UserProfileController::class, 'show']);
    Route::get('userprofile/view/{id}', [UserProfileController::class, 'view']);

    Route::get('devices/export/', [DevicesController::class, 'export']);

    Route::resource('userprofile', UserProfileController::class);
    Route::resource('devices', DevicesController::class);
    Route::resource('requestMan', ReqMaintenanceController::class);
    Route::resource('HandleRequest', HandelrequestController::class);
});

resources/views/profiles/create.blade.php
@extends('layouts/app')
@section('content')

    <div class="card-card-default">
        <div class="card-header">
            <h4>{{ isset($devices) ? 'Edit Users' : 'Create New Users' }}</h4>
        </div>
        <div class="card-body">
            @if ($errors->any())
                <div class="alert alert-danger" role="alert">
                    @foreach ($errors->all() as $error)
                        <ul class="list-group">
                            <li class="list group-item">
                                {{ $error }}
                            </li>
                        </ul>
                    @endforeach
                </div>
            @endif

            <form action="{{ route('userprofile.store') }}" method="post">
                @csrf
                @if (isset($profiles))
                    @method('PUT')
                @endif
                <div class="form-group">
                    <label for="name">User Name</label>
                    <input type="name" name="name" class="form-control" id="name" placeholder="User Name">
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Email address</label>
                    <input type="email" name="email" class="form-control" id="exampleInputEmail1"
                        aria-describedby="emailHelp" placeholder="Enter email">
                    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone
                        else.</small>
                </div>
                <input type="hidden" name="usertype" id="" value="user">
                <input type="hidden" name="isban" id="" value="0">
                <div class="form-group">
                    <label for="exampleInputPassword1">Password</label>
                    <input type="password" name="password" class="form-control" id="exampleInputPassword1"
                        placeholder="Password">
                </div>

                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    @endsection

resources/views/profiles/index.blade.php
@section('datatable')
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.23/css/jquery.dataTables.min.css">
@endsection
@extends('layouts.app')
@section('content')
    @if (session()->has('message'))
        <div class="alert alert-success" role="alert">
            {{ session()->get('message') }}
        </div>
    @endif
    <div class="d-flex justify-content-end mb-2">
        <a href="{{ route('userprofile.create') }}" class="btn btn-success">Add New Users</a>
    </div>
    <div class="card">
        <div class="card-header bg-info">
            <h4>List Of Users</h4>
        </div>
        <div class="card-body">
            <table class="table table-bordered" id="table_id">
                <thead>
                    <tr>
                        <th scope="col">User Name</th>
                        <th scope="col">Email</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($profile as $profiles)
                        <tr>
                            <td>{{ $profiles->name }}</td>
                            <td>{{ $profiles->email }}</td>

                            <td>
                                <a href="{{ url('userprofile/view/' . $profiles->id) }}" class="btn btn-primary btn-sm"><i
                                        class="fas fa-eye"></i> View</a>
                                <a href="{{ route('userprofile.edit', $profiles->id) }}" class="btn btn-success btn-sm"><i
                                        class="fas fa-user-edit"> </i>Edit</a>
                                @if ($profiles->id == 1)

                                @else
                                    @if ($profiles->isban == '0')
                                        <button class="btn btn-info btn-sm" onclick="handleDelete({{ $profiles->id }})"><i
                                                class="fas fa-universal-access"></i> Not
                                            Banned</button>
                                    @elseif($profiles->isban=='1')
                                        <button class="btn btn-danger btn-sm"
                                            onclick="handleDelete1({{ $profiles->id }})"><i class="fas fa-ban"></i>
                                            Banned</button>

                                    @endif
                                @endif
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>

            <!-- Modal -->
            <div class="modal fade" id="showModal" tabindex="-1" role="dialog" aria-labelledby="ban" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <form action="" method="POST" id="ban">
                        @csrf
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="ban">Modal title</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <input type="hidden" name="name" id="" value="{{ $profiles->name }}">
                                <input type="hidden" name="email" id="" value="{{ $profiles->email }}">
                                <input type="hidden" name="password" id="" value="{{ $profiles->password }}">
                                <input type="hidden" name="usertype" id="" value="{{ $profiles->usertype }}">
                                <input type="hidden" name="isban" id="" value=1>
                                You Want to ban The User

                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                                <button type="submit" class="btn btn-primary">Yes</button>
                            </div>
                        </div>
                    </form>
                </div>

            </div>
            <!-- Modal -->
            <div class="modal fade" id="showModal1" tabindex="-1" role="dialog" aria-labelledby="Notban" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <form action="" method="POST" id="Notban">
                        @csrf
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="Notban">Modal title</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <input type="hidden" name="name" id="" value="{{ $profiles->name }}">
                                <input type="hidden" name="email" id="" value="{{ $profiles->email }}">
                                <input type="hidden" name="password" id="" value="{{ $profiles->password }}">
                                <input type="hidden" name="usertype" id="" value="{{ $profiles->usertype }}">
                                <input type="hidden" name="isban" id="" value=0>
                                You want UnBanned This User

                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                                <button type="submit" class="btn btn-primary">Yes</button>
                            </div>
                        </div>
                    </form>
                </div>

            </div>

        </div>
    @endsection

    @section('scripts')

        <script>
            function handleDelete(id) {
                var form = document.getElementById('ban');
                form.action = '/userprofile/ban/' + id
                $('#showModal').modal('show')
            }

        </script>

        <script>
            function handleDelete1(id) {
                var form = document.getElementById('Notban');
                form.action = '/userprofile/ban/' + id
                $('#showModal1').modal('show')
            }

        </script>

    @endsection
    @section('datatablescript')
        <script src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"></script>
        <script>
            $(document).ready(function() {
                $('#table_id').DataTable();
            });

        </script>
    @endsection

resources/views/profiles/profile.blade.php
@extends('layouts/app')
@section('content')
    <a href="{{ url('/home') }}" class="btn btn-success   ">Go Back</a>
    <div class="card">
        <div class="card-header bg-info">
            User Profile
        </div>
        <div class="card-body ">
            <h5 class="card-title ">View Your Profile</h5>
            <table class="table" id="table_id">
                <thead>
                    <tr>
                        <th scope="col">First</th>
                        <th scope="col">email</th>
                        <th scope="col">Handle</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>{{ $profiles->name }}</td>
                        <td>{{ $profiles->email }}</td>
                        <td>{{ $profiles->usertype }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
@endsection
@section('datatablescript')
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.js">
    </script>

    <script>
        $(document).ready(function() {
            $('#table_id').DataTable();
        });

    </script>
@endsection

resources/views/profiles/show.blade.php
@extends('layouts.app')
@section('content')
    <form>
        <div class="form-group">
            <label for="exampleFormControlInput1">name</label>
            <input type="text" class="form-control" id="exampleFormControlInput1" value="{{ $show->name }}" disabled>
        </div>
        <div class="form-group">
            <label for="exampleFormControlTextarea1">Email</label>
            <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"
                disabled>{{ $show->email }}</textarea>
        </div>

        <div class="form-group">
            <label for="exampleFormControlInput1">User Type</label>
            <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com"
                value="{{ $show->usertype }}" disabled>
        </div>
        <div class="form-group">
            <label for="exampleFormControlInput1">Join Date</label>
            <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com"
                value="{{ $show->created_at }}" disabled>
        </div>
    </form>
@endsection